-- Initial Database Setup For Testing

CREATE TABLE SWVPTRM_UP_WEB (
      TERM VARCHAR2(100),
      PTRM VARCHAR2(100),
      PTRM_DESC VARCHAR2(200),
      PTRM_START DATE,
      PTRM_END DATE
);

INSERT INTO SWVPTRM_UP_WEB VALUES ('201520', 'R4', 'Fun Term', sysdate, sysdate + 100);
INSERT INTO SWVPTRM_UP_WEB VALUES ('201525', 'P3', 'P Term', sysdate, sysdate + 100);

CREATE TABLE SWVPTRM_UR_WEB (
      TERM VARCHAR2(100),
      PTRM VARCHAR2(100),
      PTRM_DESC VARCHAR2(200),
      PTRM_START DATE,
      PTRM_END DATE
);

INSERT INTO SWVPTRM_UR_WEB VALUES ('201510', 'R2', 'Fun Term', sysdate, sysdate + 100);

CREATE TABLE SWVPTRM_WEB (
      TERM VARCHAR2(100),
      PTRM VARCHAR2(100),
      PTRM_DESC VARCHAR2(200),
      PTRM_START DATE,
      PTRM_END DATE
);

INSERT INTO SWVPTRM_WEB VALUES ('201520', 'P3', 'P Term', sysdate, sysdate + 100);

CREATE TABLE SWVSUBJ_WEB (
    TERM VARCHAR2(100),
    PTRM VARCHAR2(100),
    SUBJ VARCHAR2(100),
    SUBJ_DESC VARCHAR2(100)
);

INSERT INTO SWVSUBJ_WEB VALUES ('201510', 'P3', 'Robotics', 'Coolest Course Ever');

CREATE TABLE SWVAREA_PSPT_WEB (
    AREA VARCHAR2(100),
    AREA_DESC VARCHAR2(100)
);

INSERT INTO SWVAREA_PSPT_WEB VALUES ('Microbiotics', 'The future of academics');

CREATE TABLE SWVINST_ASGN_SWVPTRM_WEB (
    TERM VARCHAR2(100),
    PTRM VARCHAR2(100),
    PREF_NAME VARCHAR2(100),
    CA_EMAIL VARCHAR2(100),
    PREF_FIRST_NAME VARCHAR2(100)
    PIDM NUMBER(8)
)

INSERT INTO SWVINST_ASGN_SWVPTRM_WEB VALUES ('Microbiotics', 'The future of academics', 'Kevin', 'celebikw@eckerd.edu', 'CoolGuy', '4');

CREATE TABLE SWVINST_ASGN_PTRM_WEB (
    TERM VARCHAR2(100),
    PTRM VARCHAR2(100),
    PREF_NAME VARCHAR2(100),
    CA_EMAIL VARCHAR2(100),
    PREF_FIRST_NAME VARCHAR2(100)
    PIDM NUMBER(8)
)

INSERT INTO SWVINST_ASGN_PTRM_WEB VALUES ('Microbiotics', 'The future of academics', 'Kevin', 'celebikw@eckerd.edu', 'CoolGuy', '4');

CREATE TABLE SWVSPEC_SEARCH_WEB (
    ATTR VARCHAR2(100),
    ATTR_DESC VARCHAR2(100)
)

INSERT INTO SWVSPEC_SEARCH_WEB VALUES ('Microbiotics', 'The future of academics');


CREATE TABLE SWVCAMP_UP_WEB (
    TERM VARCHAR2(100),
    PTRM VARCHAR2(100),
    CAMP VARCHAR2(100),
    CAMP_DESC VARCHAR2(100),
)

INSERT INTO SWVCAMP_UP_WEB VALUES ('201525', 'R2', 'Summer', 'Splashing fun');

CREATE TABLE SWVSECT_WEB (
    SUBJ_DESC VARCHAR2(100),
    CRN VARCHAR2(5),
    SUBJ VARCHAR2(4),
    CRSE_NUMB VARCHAR2(5),
    SEQ_NUMB VARCHAR2(3),
    CAMP VARCHAR2(3),
    BILL_HRS NUMBER,
    CRSE_TITLE VARCHAR2(30),
    DAYS VARCHAR2(7),
    MEET_TIME VARCHAR2(3),
    CAPACITY VARCHAR2(4),
    ENRL NUMBER(4),
    REMAIN NUMBER(4),
    INSTRUCT_ALL VARCHAR2(70),
    DATES VARCHAR2(11),
    LOCATION VARCHAR2(17),
    PREREQ VARCHAR2(200),
    TEXT VARCHAR2(2500),
    COURSE VARCHAR2(14),
    MEET_SCHD VARCHAR2(3),
    SESS VARCHAR2(1),
    BN_TERM VARCHAR2(3),
    CRSE_TEXT VARCHAR2(4000),
    CAPACITY_XLST NUMBER,
    ENRL_XLST NUMBER,
    REMAIN_XLST NUMBER
)

INSERT INTO SWVSECT_WEB VALUES ('Numerology', '233', 'MATH', '52', '2', 'AHH', '23423,' 'The Art of Being Cool', '4', '100', '200', '10', '5', 'Professor Coolguy', '2004', 'Armacost', 'Every single other course', 'Air Guitar: The Concepts You Never Knew About', 'Another', '40', '4', '20', 'Yet another field about textbooks', '2048234', '23423423', '23432423');




exit