-- Initial Database Setup For Testing

CREATE TABLE SWVPTRM_UP_WEB (
      TERM VARCHAR2(100),
      PTRM VARCHAR2(100),
      PTRM_DESC VARCHAR2(200),
      PTRM_START DATE,
      PTRM_END DATE
);

INSERT INTO SWVPTRM_UP_WEB VALUES ('201520', 'R4', 'Fun Term', sysdate, sysdate + 100);
INSERT INTO SWVPTRM_UP_WEB VALUES ('201525', 'P3', 'P Term', sysdate, sysdate + 100);

CREATE TABLE SWVPTRM_UR_WEB (
      TERM VARCHAR2(100),
      PTRM VARCHAR2(100),
      PTRM_DESC VARCHAR2(200),
      PTRM_START DATE,
      PTRM_END DATE
);

INSERT INTO SWVPTRM_UR_WEB VALUES ('201510', 'R2', 'Fun Term', sysdate, sysdate + 100);

CREATE TABLE SWVPTRM_WEB (
      TERM VARCHAR2(100),
      PTRM VARCHAR2(100),
      PTRM_DESC VARCHAR2(200),
      PTRM_START DATE,
      PTRM_END DATE
);

INSERT INTO SWVPTRM_WEB VALUES ('201520', 'P3', 'P Term', sysdate, sysdate + 100);

CREATE TABLE SWVSUBJ_WEB (
    TERM VARCHAR2(100),
    PTRM VARCHAR2(100),
    SUBJ VARCHAR2(100),
    SUBJ_DESC VARCHAR2(100)
);

INSERT INTO SWVSUBJ_WEB VALUES ('201510', 'P3', 'Robotics', 'Coolest Course Ever');

CREATE TABLE SWVAREA_PSPT_WEB (
    AREA VARCHAR2(100),
    AREA_DESC VARCHAR2(100)
);

INSERT INTO SWVAREA_PSPT_WEB VALUES ('Microbiotics', 'The future of academics');

CREATE TABLE SWVINST_ASGN_SWVPTRM_WEB (
    TERM VARCHAR2(100),
    PTRM VARCHAR2(100),
    PREF_NAME VARCHAR2(100),
    CA_EMAIL VARCHAR2(100),
    PREF_FIRST_NAME VARCHAR2(100)
    PIDM NUMBER(8)
)

INSERT INTO SWVINST_ASGN_SWVPTRM_WEB VALUES ('Microbiotics', 'The future of academics', 'Kevin', 'celebikw@eckerd.edu', 'CoolGuy', '4');

CREATE TABLE SWVINST_ASGN_PTRM_WEB (
    TERM VARCHAR2(100),
    PTRM VARCHAR2(100),
    PREF_NAME VARCHAR2(100),
    CA_EMAIL VARCHAR2(100),
    PREF_FIRST_NAME VARCHAR2(100)
    PIDM NUMBER(8)
)

INSERT INTO SWVINST_ASGN_PTRM_WEB VALUES ('Microbiotics', 'The future of academics', 'Kevin', 'celebikw@eckerd.edu', 'CoolGuy', '4');

CREATE TABLE SWVSPEC_SEARCH_WEB (
    ATTR VARCHAR2(100),
    ATTR_DESC VARCHAR2(100)
)

INSERT INTO SWVSPEC_SEARCH_WEB VALUES ('Microbiotics', 'The future of academics');




exit